### ISSUE TITLE
beforeSend method should have option to fail/cancel send

### ISSUE THREAD

**Issue by mm-gmbd** [electricimp/MessageManager#1]
The `beforeSend` method is a nice way to wrap middleware into the message-sending process, but I need the ability to cancel the send based on the outcome of the `beforeSend` function. For example, if I am running below a certain memory threshold, I need the ability to automatically fail the message to ensure that I don't run out of memory. This was more necessary with Bullwinkle because of how memory intensive it was, but I think is still a necessary capability of MessageManager (and without it, we can run into some other race conditions when used with ImpPager).

**Comment by mm-gmbd** [comment]
FYI -- I've added the following `.fail` public method to MessageManager to accomplish this:

```
const MM_ERR_USER_FORCED_FAIL       = "User forced error"

...

    // Automatically causes the provided message to fail
    //
    // Parameters:
    //      msg             The message object to fail.
    //
    // Returns:             Nothing
    function fail(msg) {
        _callOnErr(msg, MM_ERR_USER_FORCED_FAIL);
    }
```

**Comment by ppetrosh** [comment]
Thanks for the feedback. This makes sense to me and I thought of it myself. Let's just call this callback "dispose" (as we already similar one in beforeRetry call)? Will address this request shortly today.

**Comment by ppetrosh** [comment]
And the reason why I propose to call it "dispose" is that I don't want this message to show up again in the onFail callback (s). I already decided to cancel or remove it from the processing loop and I don't want it to bother me again.

**Comment by mm-gmbd** [comment]
@ppetrosh -- although this may seem silly, I have a use case for automatically failing the message rather than simply disposing of it, although I think both probably have their merits. Simply put, when used in conjunction with ReplayManager, there is a race condition that is best solved when I can cause the messages to automatically fail (and have their `onFail` handlers triggered). We can discuss further if you're still on the fence about having the option to truly fail.

**Comment by mm-gmbd** [comment]
FYI -- I've made the changes on my branch if you'd like for me to open a PR:

```
// Calls the before send handler and sends the message
    //
    // Parameters:          Message to be resent
    //
    // Returns:             The message
    function _send(msg) {
        local send = true
        if (_isFunc(_beforeSend)) {
            _beforeSend(msg,
                function/*enqueue*/() {
                    _enqueue(msg)
                    send = false
                },
                function/*dispose*/() {
                    send = false
                },
                function/*fail*/() {
                    _callOnErr(msg, MM_ERR_USER_FORCED_FAIL)
                    send = false
                }
            )
        }

        if (send) {
            _sendMessage(msg)
        }
        return msg
    }

...

// tries to send the message, and executes the beforeRerty handler
    //
    // Parameters:          Message to be resent
    //
    // Returns:             Nothing
    function _retry(msg) {
        _log("Retrying to send: " + msg.payload.data)

        local send = true
        local payload = msg.payload

        if (_isFunc(_beforeRetry)) {
            _beforeRetry(msg,
                function/*skip*/(interval = null) {
                    msg._nextRetry = time() + (interval ? interval : _retryInterval)
                    send = false
                },
                function/*dispose*/() {
                    // User requests to dispose the message, so drop it on the floor
                    delete _retryQueue[payload["id"]]
                    send = false
                },
                function/*fail*/() {
                    _callOnErr(msg, MM_ERR_USER_FORCED_FAIL)
                    send = false
                }
            )
        }

        if (send) {
            msg.tries++
            delete _retryQueue[payload["id"]]
            _sendMessage(msg)
        }
    }
```

**Comment by ppetrosh** [comment]
Hi Max, what's use case that needs failing the message? Can you please describe it for me?

And thanks for proposing the changes. This looks pretty straightforward. The only thing I though of is that uses have to deal with too many callbacks. Does it make sense to have dispose with optional parameter "fail" which causes the onFail to be called if specified: 

`
                function/*dispose*/(fail) {
...
                }
            )
`

which by default silently disposes the message. What do you think?

**Comment by mm-gmbd** [comment]
Calling `dispose` with a fail option is fine with me. Or maybe making a `fail` that has a "silent" option would be more straightforward. Either way is okay :)

As for the use case, it comes from our specific project (which you're familiar with), but I'll try to generalize:

- I have new data that is generated every second by the device that I attempt to send to the Agent
- That new data is always an updated "total" (you can think of it like a car odometer that is always incrementing)
- The Agent remembers the last "total" and calculates the incremental between that and the new data from the Device (and then does some math based on that)
- With `ReplayMessenger`, I want to ensure that after coming online (after being offline for some time) I replay the new data to the Agent **in order**
- When I fall offline, I set a global saying "automatically fail all messages"
- When I come back online, I keep that global set until the data that has been logged has been replayed successfully, **otherwise**, one of the newly generated datapoints will update the "total" on the Agent, and then all of the datapoints that need to be replayed will be *less than* the Agent total and then all of the math gets screwed up

Does that make sense?

**Comment by ppetrosh** [comment]
Max, thanks for providing the use case it's very helpful to understand you are trying to achieve. 

However how does the fail() option help here? What prevents you from implementing this just a dispose handler?

To be specific, when you fail flag is on, what's going to happen with the messages being sent? Are you going to queue them for a later retry (when all the replayed messages are ACKed)? If so, you can do that with enqueue() handlers passed to the beforeSend callback. Or do you handle them on the app side and drop from the MessageManager processing loop, which can be achieved by dispose handler now). I don't see anything else you can do there. Do you understand my point/confusion?

Probably some code samples would make it more clear to me.

**Comment by ppetrosh** [comment]
Oh I think I understand why you'd need the onFail to be called in this case...

So to implement what you just described you create the MessageManager instance and define it's beforeSend callback to call fail() if the "automatically fail" flag is on. Which results in ReplayMessenger._onFail() called and the message got queued in the SPIflash. Is my understanding correct?

If so, I still have a question. Can we consider using the memory based retry queue as I described above to store them while we have no connectivity issues and flush them on the SPI, if/once something wrong happens? Did you think of this scenario? This would help to optimize the SPIflash wear and won't require any new new handlers. What do you think?

**Comment by ppetrosh** [comment]
@mm-gmbd, please confirm my understanding stated above. Thanks!
