### ISSUE TITLE
.bindenv missing

### ISSUE THREAD

**Issue by mm-gmbd** [electricimp/MessageManager#10]
Hey @ppetrosh - looks like there is a `.bindenv` missing on [line 756](https://github.com/electricimp/MessageManager/blob/master/MessageManager.class.nut#L756):

```squirrel
        if (name in _on) {
            local handler = _on[name];
            if (_isFunc(handler)) {
                handlerFound = true;
                handler(payload, function/*reply*/(data = null) {
                    replied = true;
                    error = _partner.send(MM_MESSAGE_TYPE_REPLY, {
                        "id"   : payload["id"],
                        "data" : data
                    }); //need .bindenv(this) here otherwise error "_partner not found"
                });
            }
        }
```

I'll take care of this in the open PR.

**Comment by ppetrosh** [comment]
Good catch! Wow, in theory, you are right. But I don't get this error on my local test application, that uses reply all the time. In wondering why. Can you please also add a test to address this issue? Thanks!

**Comment by mm-gmbd** [comment]
I saw the error in my application but didn't track down exactly why it was happening (but adding the `.bindenv` fixed it). I'll try to add a test case to address this, but it may take some time (busy busy).

**Comment by ppetrosh** [comment]
Don't worry, Max. Let me take care of the test myself today. I want to reproduce it on a test case. Thanks!

**Comment by mm-gmbd** [comment]
Thanks, Pavel!

**Comment by ppetrosh** [comment]
No, I don't understand this. The following code:

Agent:

```
#require "MessageManager.class.nut:0.9.0"

local mm = MessageManager()

mm.on("name", function(msg, reply) {
    server.log("Message received: " + msg.data)
    reply("Got it!")
})

```

Device:

```
#require "MessageManager.class.nut:0.9.0"

local mm = MessageManager()

mm.onReply(
    function(msg, response) {
        server.log("Received reply: " + response)
    }
)

mm.send("name", 123);
```

Works perfectly fine with no error and I don't know why:

```
2017-02-04 00:18:10+0000 [Server] Agent restarted: reload.
2017-02-04 00:18:10+0000 [Server] Downloading new code; 5.32% program storage used
2017-02-04 00:18:11+0000 [Agent]  Message received: 123
2017-02-04 00:18:11+0000 [Device] Received reply: Got it!
```

**Comment by ppetrosh** [comment]
So I don't even know how to write a test that verifies this.

**Comment by ppetrosh** [comment]
Resolved on develop. Will be release with all other changes.
