### ISSUE TITLE
Allow deregistering of handlers

### ISSUE THREAD

**Issue by mm-gmbd** [electricimp/MessageManager#11]
It would help to have a way to de-register handlers, otherwise I have some code that I have to make very state-dependent. I'm starting with the `on` handler (modified code below), but it probably makes sense for all handlers.

```squirrel
function on(name, handler=null) {
        if (handler) {
          _on[name] <- handler;
        } else {
          if (name in _on) {
            delete _on[name];
          }
        }
    }
```

**Comment by ppetrosh** [comment]
To deregister any handler (not only _on) you can already pass `null` and it won't be called anymore.
