### ISSUE TITLE
possible beforeSend race condition?

### ISSUE THREAD

**Issue by mm-gmbd** [electricimp/MessageManager#2]
A question about the implementation of `_send` relative to the `_beforeSend` middleware. 

The second argument supplied to `_beforeSend` is a function that can be called to send the message after the "before" function completes, which queues the message and sets "send" to false (so that it will not be called within this call to `_send` (I believe is the idea behind the implementation). The problem is that `send = false` happens within the function provided to `_beforeSend`, so the `if (send)` will evaluate to true if there is `_beforeSend` is asynchronous.

```javascript
// Calls the before send handler and sends the message
    //
    // Parameters:          Message to be resent
    //
    // Returns:             The message
    function _send(msg) {
        local send = true
        if (_isFunc(_beforeSend)) {
            _beforeSend(msg, function/*enqueue*/() {
                _enqueue(msg)
                send = false
            })
        }

        if (send) {
            _sendMessage(msg)
        }
        return msg
    }
```

**Comment by mm-gmbd** [comment]
Is the fix as simple as moving `send = false` to before `_beforeSend` is called?

```javascript
// Calls the before send handler and sends the message
    //
    // Parameters:          Message to be resent
    //
    // Returns:             The message
    function _send(msg) {
        local send = true
        if (_isFunc(_beforeSend)) {
            send = false
            _beforeSend(msg, function/*enqueue*/() {
                _enqueue(msg)
            })
        }

        if (send) {
            _sendMessage(msg)
        }
        return msg
    }
```

**Comment by ppetrosh** [comment]
Hi Max, 

Thank you very much for carefully reviewing the code and digging into the details! This is very helpful.

I hate to do this, but let me try to push back on this particular issue:

_beforeSend is a synchronous call with regards to _send function and thus all the synchronous calls from _beforeSend are sync with regards to _send as well. So the /*enqueue*/ callback (if called synchronously) is guaranteed to complete before further if (send) check is called. So there is no evident issues that I can see there.

And moreover the proposed change doesn't seem to be correct. You only want to enqueue message if the /*enqueue*/ callback is called by the user.

Do you agree?

**Comment by mm-gmbd** [comment]
No problem with pushing back! :smile:

I did not that if everything was synchronous then this would work out. I think my issue is because the flexibility is limited so that asynchronous calls can't be made. However, I I think further into it, you probably don't want to *force* the user to have to make the callback (i.e. it should fire *eventually* if the */enqueue/* callback isn't called), and if it is asynchronous you don't know how long / if the callback will be called, then you would have to use timers, and then you'd have to determine an appropriate amount of time for the timer, and on and on...

So, it probably makes sense for this to stay as is. But, now I'm wondering, what is the purpose of providing the */enqueue/* callback anyway? As far as I can tell, it simply delays the message from sending (by putting it back on the queue and causing a retry to happen).

**Comment by ppetrosh** [comment]
Oh, that's a good question. The idea of having /*enqueue*/ was inspired by an idea that came from your guys. At some point Austin brought a use case when he wanted to delay delivery of some messages based on the fact that some previously send ones didn't arrive yet. This is a reasonable request if we want to do our best to preserve the order of messages. Other than that I don't see any other use cases for enqueue. 

But I anticipated that eventually someone will ask for it so I wanted it to be a part of the APIs. If you have any better ideas please let me know.

Thanks!

**Comment by mm-gmbd** [comment]
Sounds good to me, I'll shout over the cube and figure out what Austin was thinking. Probably safe to close for now. Thanks!
