### ISSUE TITLE
Problem with the onTimeout handler

### ISSUE THREAD

**Issue by dbukhmastov** [electricimp/MessageManager#22]
When setting the timeout (messageTimeout param of MessageManager constructor or function wait(duration) of onTimeout handler), the onTimeout handler fires a second later than it is set.
#### Scenario:
Agent:
```squirrel
local ts = 0;
local waitingTime = 2;
local mm;
local onPartnerConnected = function(reply) {
    mm.send("channel", "message");
};
mm = MessageManager({
    "onPartnerConnected": onPartnerConnected.bindenv(this),
    "messageTimeout":     1
});
mm.onTimeout(function(msg, wait, fail) {
    if (ts == 0) {
        ts = time();
        wait(waitingTime);
    } else {
        server.log("Estimated waiting time: " + waitingTime);
        server.log("Real waiting time: " + (time() - ts));
    }
}.bindenv(this));
mm.send("channel", "message");
```
Device:
```squirrel
local mm = MessageManager({
    "connectionManager": ConnectionManager()
});
mm.on("channel", function(message, reply) {
    imp.sleep(8);
    reply("message");
}.bindenv(this));
```
#### Log:
[Agent] Estimated waiting time: 2
[Agent] Real waiting time: 3
#### Tests:
This issue affects 
class: tests/compatibility/CallbacksTestCase.nut method: testOnTimeout()
class: tests/compatibility/ConstructorTestCase.nut method: testMessageTimeout()
class: tests/compatibility/LocalCallbacksTestCase.nut method: testOnTimeout()

**Comment by ppetrosh** [comment]
This one has already been fixed too.
