### ISSUE TITLE
Reorder arguments to onFail

### ISSUE THREAD

**Issue by mm-gmbd** [electricimp/MessageManager#3]
Hey @ppetrosh - it would be nice if we could re-order the arguments to onFail so that they were backwards-compatible with Bullwinkle (I don't think it reduces functionality in any way):

```
function _callOnErr(msg, error) {

        local hasHandler = false
        local checkAndCall = function(f) {
            if (_isFunc(f)) {
                hasHandler = true
                f(msg, error, function/*retry*/(interval = null) { // change to f(error, msg, function/*... for backwards compatibility
                    msg._nextRetry = time() + (interval ? interval : _retryInterval)
                    _enqueue(msg)
                })
            }
        }

        checkAndCall(msg._onFail)
        checkAndCall(_onFail)

        if (!hasHandler) {
            // Error handler is not set. Let's check the autoretry.
            if (_autoRetry && (!_maxAutoRetries || msg.tries < _maxAutoRetries)) {
                msg._nextRetry = time() + _retryInterval
                _enqueue(msg)
            }
        }
    }
```

**Comment by ppetrosh** [comment]
Hi Max,

I didn't like the bullwinkle order that's why I changed it here. I believe we should take this chance of creating the brand new library to make it all consistent so that people don't have to look at the code or documentation everytime they write something. The proposed idea is to always pass the message in question as the first parameter and all others to follow.

Or we should change the order everywhere. But I believe all these callbacks are all about a message, which should go first.

What do you think? How important is it to preserve this compatibility for you guys?

**Comment by mm-gmbd** [comment]
I understand the reason for including message first as it is the main "subject". Although it is nice, it's not necessarily important to preserve compatibility. Really it was just to reduce the amount of work on my end (aka being selfish :wink:).

**Comment by ppetrosh** [comment]
I see you argument. But unfortunately you need to modify the code anyway (for example onReply has a different signature as we don't send the entire message back and forth just to reply or acknowledge it anymore). How critical is the issue for you?

If it manageable, I'd definitely try to keep the consistent "proper" API of a priority. A separate question would be if these APIs are really consistent and appropriate for its purpose. If you have any concerns about it, I'd be happy to discuss it.

Thanks!

**Comment by mm-gmbd** [comment]
Considering Bullwinkle could be chained and the arguments could either be anonymous functions, already-defined functions, and function factories, (all of which could be multi-line) I didn't end up finding a nice global find/replace that would work. So, agreed that I have to touch the entire codebase as it stands anyway, I was just trying to reduce what actually needed to be done for each call to MessageManager (less steps, less chances to screw it up :smile:).

I agree in keeping the API "proper" a priority, and I think so far things appear to be all good (although, I do have a question about `onReply`, which I will open a separate issue about).

Closing!

**Comment by mm-gmbd** [comment]
Actually, I just realized why the `onReply` makes sense now. At first I thought the 2nd argument was redundant, but that's just because I was still thinking in terms of Bullwinkle.
