### ISSUE TITLE
Make "reply" a first-class citizen in terms of agent/device communication

### ISSUE THREAD

**Issue by thomaskoehn-kisi** [electricimp/MessageManager#31]
`reply` as passed into `.on` does currently not allow for much control over the message. You dont know whether it arrived, you cannot retry etc.

My request is to make `reply` a first-class citizen of MessageManager (ideally also Bullwinkle, but I assume you dont want to touch this anymore). From a "user" perspective (i.e., someone who implements the library), `reply` should work no different than `.send`, in that it returns a package and let's you attach `.onFail` and similar callbacks (speaking in Bullwinkle terms here; of course, it might need a few restrictions, like no `.onReply` – or maybe it does make sense, not sure). This also has the effect that `reply` can still work in the simple ways as before, if someone chooses to not make use of the returned package.

**Comment by betzrhodes** [comment]
If a message needs to be a first-class citizen don't use `reply`, send a new message instead.

**Comment by thomaskoehn-kisi** [comment]
@betzrhodes there is an internal support ticket about this topic, and in that we were at the point already that you mentioned, and decided it is not a good path to go. I'd definitely urge you to fix `reply` instead.

**Comment by betzrhodes** [comment]
There has been internal discussion around reply as a first-class citizen. However it is very low priority since there is a work around.

**Comment by thomaskoehn-kisi** [comment]
It would probably even reduce code space (which we'd deem very valuable) if you unified this...
