### ISSUE TITLE
Call `_onDataReceived` handler with full payload

### ISSUE THREAD

**Issue by mm-gmbd** [electricimp/MessageManager#4]
This is another one that is mainly for backwards compatibility with Bullwinkle (so I don't have to go through and update the entire codebase). Is there a reason the `_onDataReceived` handler only provides the "data" portion of the payload rather than the payload itself to the registered `.on` handler?

Again, I don't think this would result in any performance hits and would make code updates easier.

```
function _onDataReceived(payload) {

        // Call the on callback
        local name = payload["name"]
        local data = payload["data"]
        local replied = false
        local handlerFound = false
        local error = 0

        if (name in _on) {
            local handler = _on[name]
            if (_isFunc(handler)) {
                handlerFound = true
                handler(data, function/*reply*/(data = null) { //CHANGE TO handler(payload, ...) for Bullwinkle backwards compatibility
                    replied = true
                    error = _partner.send(MM_MESSAGE_NAME_REPLY, {
                        "id"   : payload["id"]
                        "data" : data
                    })
                })
            }
        }

        // If message was not replied, send the ACK
        if (!replied) {
            error = _partner.send(MM_MESSAGE_NAME_ACK, {
                "id" : payload["id"]
            })
        }

        // No valid handler - send NACK
        if (!handlerFound) {
            error = _partner.send(MM_MESSAGE_NAME_NACK, {
                "id" : payload["id"]
            })
        }

        if (error) {
            // Responding to a message failed
            // though this is a valid case
            _log("Responding to a message failed")
        }
    }
```

**Comment by mm-gmbd** [comment]
Also, this would allow the partner to see the "created" time of the message, which one could argue that the receiving side should be able to know.

**Comment by mm-gmbd** [comment]
@ppetrosh - thoughts?

**Comment by ppetrosh** [comment]
I was the one that originally thought the same. So this request seems to be perfectly valid to me.
But I've heard some concerns like "you send one thing and receive something else". Which I bought at that time. But now thinking it over once again I realized that for example with email. You send a text and receive the entire package with all the headers and meta-information along with the original payload. So I'd just accept it and fix unless I hear any objections.

@betzrhodes, I believe it was you whom we initially discuss it with, right? Do you have any objections?

**Comment by mm-gmbd** [comment]
I'm in favor for the entire payload, and I'd like to do the same for the `onReply` handler (opening another ticket for that now).

**Comment by ppetrosh** [comment]
onReply handler receives the full payload, so it's not an issue there, unless I'm missing something.

**Comment by mm-gmbd** [comment]
I've opened #5 to discuss, but I don't think that's the case. We can pick up the discussion there.

**Comment by ppetrosh** [comment]
got it, thanks!
