### ISSUE TITLE
Supply `onReply` callback with full payload

### ISSUE THREAD

**Issue by mm-gmbd** [electricimp/MessageManager#5]
If the change in #4 is adopted, then I think it follows that the same should happen for the `onReply` callback. Currently, the arguments are the original message and the response data portion of the payload. First, I think having the entire payload (rather than just the data portion) allows the user implementation to be more flexible (access to the `created` timestamp, etc), and it seems a bit odd to provide the full *sent* message, but only the data portion of the response (so, it would help in making the arguments more consistent).

```javascript
// A handler for message replies
    // Calls both user provided onAck and onReply handlers
    //
    // Parameters:          Payload containing id and response data for reply
    //
    // Returns:             Nothing
    function _onReplyReceived(payload) {
        local id = payload["id"]
        if (id in _sentQueue) {
            local msg = _sentQueue[id]

            // Make sure to call acknowledgement handlers first
            _isFunc(msg._onAck) && msg._onAck(msg)
            _isFunc(_onAck) && _onAck(msg)

            // Then call the global handlers
            _isFunc(msg._onReply) && msg._onReply(msg, payload["data"]) //should be msg._onReply(msg, payload) 
            _isFunc(_onReply) && _onReply(msg, payload["data"]) //should be _onReply(msg, payload)

            delete _sentQueue[id]
        }
    }
```

**Comment by ppetrosh** [comment]
Please look at _onDataReceived. What you get in the onReplyReceived is the message id and response. And I only return response by selecting payload["data"]. The first parameter is the full original message.

So to be honest I don't see an issue here. Please correct me if I'm wrong. Thanks!

**Comment by mm-gmbd** [comment]
The first parameter is the full original *sent* message, but what I'm saying is that the second parameter should be the full *return* message, rather than just the *data* portion of the return message. If it was to stay the same, then the onDataReceieved would receive the full data payload from the `_partner`, but the `onReply` would not get the full response (just the data portion). Apologies if I'm not being clear (or am just missing something).

**Comment by ppetrosh** [comment]
Hi Max,

If you look at `_onDataReceived` the full return message is:

```
{
   "id"   : originalMessageId,
   "data" : responseMessage
}
```

I'm not sending anything else other than the message id, which is already there in the first first parameter. What else are you looking for?

**Comment by ppetrosh** [comment]
So to be clear (and this is a difference to Bullwinkle) all the service messages like reply and ACK/NACK don't include anything but a message ID, message type (REPLY, ACK or NACK) and an optional response if any. For the sake of optimizing the traffic, we are not sending any meta-information or the original message payload.

So the full payload message request is only valid for the "on" handler, which includes the message payload and that was already fixed in #4.

So let me close this one as not an issue. However please feel free to reopen it I'm wrong somewhere, which can easily be the case. Thank you!

**Comment by mm-gmbd** [comment]
Although this probably outside of the intention of `MessageManager`, I was considering adding some meta-information to the response in the `beforeReply` callback. The *sent* message has a `created` timestamp which can be useful, and I was thinking that a response timestamp could also be useful, and was going to add to the metadata in the `beforeReply` rather than to the message payload itself.

Although this would be nice, it is not necessary for me, so we can leave as is.

**Comment by ppetrosh** [comment]
Max, you can provide any information whatever meta or useful in the reply callback. And it will be delivered to the other party as a part of the reply payload. You are not limited to strings, and can use any objects there. Does it work for your use case?

**Comment by mm-gmbd** [comment]
Yes -- apologies, this again was for more of not having to touch the entire codebase, but I went ahead and did it and it wasn't as bad as I expected :smile: feel free to close!

**Comment by ppetrosh** [comment]
Great. Thanks for confirming, Max!
