### ISSUE TITLE
"onReply" not getting called race condition

### ISSUE THREAD

**Issue by mm-gmbd** [electricimp/MessageManager#6]
Per-message `onReply` handler not getting called due to race condition because private method `_onAckReceived` is deleting message from sentQueue before `_onReplyReceived` has a chance to process.

The "ack" is always sent back, and with the current implementation it will always delete the message from the sentQueue before the `_onReplyReceived` handler is called.

The logs I get from the following added server.logs are as follows:

1. "1 Deleting message id 2 from the sent queue"
2. "Received reply for message id 2"
3. "_sentQueue contents: {}"

```

// A handler for message acknowledgement
    //
    // Parameters:          Acknowledgement message containing original message id
    //
    // Returns:             Nothing
    function _onAckReceived(payload) {
        local id = payload["id"]
        if (id in _sentQueue) {
            local msg = _sentQueue[id]

            _isFunc(msg._onAck) && msg._onAck(msg)
            _isFunc(_onAck) && _onAck(msg)

            // Delete the acked message from the queue
            server.log("1 Deleting message id "+id+" from the sent queue")
            delete _sentQueue[id]
        }
    }

function _onReplyReceived(payload) {
        server.log("Received reply for message id "+payload["id"]);
        local id = payload["id"]
        server.log("_sentQueue contents: "+JSONEncoder.encode(_sentQueue))
        if (id in _sentQueue) {
            server.log("It's in the sent queue!")
            local msg = _sentQueue[id]
            server.log("And its name is: "+msg.payload.name);

            // Make sure to call acknowledgement handlers first
            _isFunc(msg._onAck) && msg._onAck(msg)
            _isFunc(_onAck) && _onAck(msg)

            // Then call the global handlers
            server.log("Calling the onReply handlers!")
            _isFunc(msg._onReply) && msg._onReply(msg, payload["data"])
            _isFunc(_onReply) && _onReply(msg, payload["data"])

            server.log("2 Deleting message id "+id+" from the sent queue")
            delete _sentQueue[id]
        }
    }

```

**Comment by mm-gmbd** [comment]
@ppetrosh -- comments?

**Comment by ppetrosh** [comment]
For some reason, these two issues that you filed, went out of my radar. I'm sorry for that!

The current implementation sends the acknowledgement only if the message wasn't replied. Please refer to [`_onDataReceived `](https://github.com/electricimp/MessageManager/blob/master/MessageManager.class.nut#L763-L765) implementation.

Please let me know if you feel like it's still an issue. Otherwise, please close it.

**Comment by ppetrosh** [comment]
Please note that the `reply` handler needs to be called synchronously. Let me know if this limitation doesn't work for your use cases.

**Comment by mm-gmbd** [comment]
Hey @ppetrosh -- the reply handler being called asynchronously is definitely a requirement. It *is* possible to accomplish asynchronous replies by starting a new message from the *partner* side (that I would be expecting the reply from), but it is my opinion that it over-complicates things...

A general use case:

- From Device to Agent:
  - Device sends a message to the Agent
  - Agent sends asynchronous request for data from other service (i.e. weather data)
  - Agent replies with information to device for device to take action

**Comment by ppetrosh** [comment]
Got it, makes sense to me. This is what Aron anticipated. I don't expect any issues with making this particular callback asynchronous. Will take care of it.

Are there any other callbacks/handlers that you think would make sense to have asynchronous? Can you review the API, when you have time from this perspective?

Thank you!

**Comment by ppetrosh** [comment]
BTW, for a perfectly valid reason Bullwinkle alwasy had the same limitation https://github.com/electricimp/Bullwinkle:

> The retry parameter is a method that can be invoked to retry sending the message in a specified period of time. This method must be called synchronously if it is to be called at all. If the retry() method is not called the message will be expired.

**Comment by ppetrosh** [comment]
I don't see any way to address this request so far.

Even if you add a flag "acked" to the DataMessage object and then will drop the acknowledged messages on timeout (eventually you have to drop as you can't hold them forever). And if you reply "too" late, the response will be ignored, which may be confusing for users.

The use case that you described can easily be implemented without async replies. From device POV all the agent responses are async anyway. So asynchronously sending a message when agent receives the result back from the external service should work pretty good. In both cases you register a separate callback for the response.

Having said that I'm considering of closing this as "Won't fix". If you see any working options please let me know.

**Comment by mm-gmbd** [comment]
Hey @ppetrosh -- can there be a request level `replyTimeout`? For example, if the `onReply` handler is set, but not responded to within the `replyTimeout`, then it is removed from there queue. Does this make sense?

**Comment by ppetrosh** [comment]
Max, I believe this could be an option. However I'd probably call the replyTimeout handler if a message was not replied in time regardless of whether onReply was set or not. Does it make sense? If so, I'll go and implement this.

**Comment by ppetrosh** [comment]
@mm-gmbd can you please clarify. Is it something that you have a use case for already or is it more a 'theoretical' problem? If the latter is the case then I would probably propose to postpone the fix until you have an actual and clear need for this feature. What do you think?

**Comment by mm-gmbd** [comment]
Hey @ppetrosh -- currently, this is an actual problem for my use case. My code expects the `onReply` handler to get called in a number of instances, but that doesn't happen because the `reply` handler gets called asynchronously. The `replyTimeout` feature - which should have a sensical default of something like 10 seconds but also be configurable per request (and globally configurable) - I think helps to solve this issue.

**Comment by deldrid1** [comment]
+1 for this feature, as I got bit over the weekend....  I want to `mm.send` from the device to agent, and then use `reply` to respond to the `mm.send` from an `http.put.sendasync`.  

In my opinion, async reply either needs to be supported, throw an obvious error if used incorrectly, or reply removed altogether from the lib in my opinion.

**Comment by deldrid1** [comment]
@ppetrosh - can we make sure that we are on the same page about `reply` vs. `retry`?

There are no documentation warnings about using reply asynchronously.

**Comment by ppetrosh** [comment]
@deldrid1 you are right. `reply` is not documented for Bullwinkle, but it has the same problem:

1. If a message was ACKed **AND**
2. Receiver had onReply set **AND**
3. Reply arrived later **THEN** the message will be reported as timed out.

As discussed above we can replicate and enhance this functionality by introducing onReplyTimeout handler, which everyone will have to pay for with an additional footprint.

I'm not arguing and will implement it along with other updates discussed with Max before.

**Comment by deldrid1** [comment]
@ppetrosh - did you ever take a look at implementing asynchronous `reply` via `onReplyTimeout` and maybe just not push the library updates to github?

I am working on finishing touches for ReplayMessenger.  One of the features I would like to add is an option for `RM.send()` to wait for a MM reply (perhaps with an affirmative data packet) for success (and deleting replays from the SPIFlashLogger, etc.), instead of just ACK.

The use case for this is what is recorded above - I may have more SPIFlashLogger data than I do agent.save() (or even all of Agent RAM).  I'd like to wait for an async MM.onReply call (which will be called when the data has been verified as written to a 3rd party service like Firebase) before deleting data from the SPIFlashLogger.

**Comment by ppetrosh** [comment]
@deldrid1 `reply` can now be called asynchronous. And for such messages you can specify message-local timeouts, which are essentially TTLs, that overwrite defaults (I don't like the idea of having two different timeouts). I feel like that should address your use case. Right?

**Comment by deldrid1** [comment]
I think that takes care of it!
