### ISSUE TITLE
Add optional custom error message to `drop` in beforeSend and beforeFail

### ISSUE THREAD

**Issue by mm-gmbd** [electricimp/MessageManager#7]
For better logging and debugging, I'd like the option to send a custom error message (rather than the default "MM_ERR_USER_DROPPED_MESSAGE") to the `drop` method provided to beforeSend and beforeFail.

**Comment by mm-gmbd** [comment]
@ppetrosh -- comments?

**Comment by ppetrosh** [comment]
Hi @mm-gmbd, I'm sorry for the delayed answer. Not sure I understand, where is the message supposed to be sent? Why can't you log it from the `beforeSend` or `beforeFail` functions?

**Comment by ppetrosh** [comment]
I got it from the PR https://github.com/electricimp/MessageManager/pull/8. Makes sense to me.

**Comment by ppetrosh** [comment]
Resolved on develop. Will be released with all other changes.
